from aiogram.types import KeyboardButton, ReplyKeyboardMarkup


LANGUAGE_NAMES = {
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
    "es": "🇪🇸 Español",
    "hy": "🇦🇲 Հայերեն",
}

TEXTS = {
    "ru": {
        "menu": "Главное меню TrueLoto",
        "participate": "Участвовать",
        "status": "Мой статус",
        "rules": "Правила",
        "language_selection": "Выбор языка",
        "back": "⬅️ Назад",
        "participate_soon": "Функция участия скоро появится.",
        "rules_text": "Правила TrueLoto будут опубликованы перед запуском первого раунда.",
        "name": "Имя",
        "registration_date": "Дата регистрации",
        "participation_status": "Статус участия",
        "winning_chance": "Шанс на победу",
        "not_participating": "Не участвуете",
        "language_selected": "Язык выбран: Русский.",
        "choose_participation": "Выберите сценарий участия:",
        "join_draw": "Участвовать в розыгрыше",
        "decline_prize": "Отказаться от выигрыша",
        "test_deposit": "Внести оплату",
        "confirm_test_payment": "Подтвердить оплату",
        "deposit_step": "Тестовый режим. Следующий шаг — внесение депозита.",
        "payment_step": "Тестовый депозит отмечен. Подтвердите оплату.",
        "waiting_draw": "Поздравляем! Ожидайте начала розыгрыша. Розыгрыш состоится: {draw_datetime}",
        "decline_complete": "Спасибо за ваше благородство и помощь в развитии нашей экосистемы! Вам будут начислены баллы в карму.",
        "status_waiting_draw": "Ожидаете розыгрыш",
        "status_declined": "Отказались от выигрыша",
        "draw_finished": "Розыгрыш завершён. Участие в следующем раунде снова доступно.",
        "draw_winner": "Поздравляем с победой! Тестовый результат: вы выбраны победителем этого раунда.",
        "draw_not_winner": "В этот раз вам не повезло, но не расстраивайтесь, Ваши шансы теперь будут увеличены в следующем раунде! Проверить шанс победы вы можете, нажав на кнопку «Мой статус».",
        "test_notice": "⚠️ ТЕСТОВАЯ ВЕРСИЯ\nПлатёжные системы, реальные оплаты, финансовые сделки и ссылки не используются. Бот не запрашивает платёжные реквизиты, данные карт, документы или пароли. Все кнопки предназначены только для тестирования. Никаких финансовых операций совершаться не будет.",
    },
    "en": {
        "menu": "TrueLoto main menu",
        "participate": "Participate",
        "status": "My status",
        "rules": "Rules",
        "language_selection": "Language selection",
        "back": "⬅️ Back",
        "participate_soon": "Participation will be available soon.",
        "rules_text": "TrueLoto rules will be published before the first round starts.",
        "name": "Name",
        "registration_date": "Registration date",
        "participation_status": "Participation status",
        "winning_chance": "Winning chance",
        "not_participating": "Not participating",
        "language_selected": "Language selected: English.",
        "choose_participation": "Choose a participation option:",
        "join_draw": "Join the draw",
        "decline_prize": "Decline the prize",
        "test_deposit": "Make a test deposit",
        "confirm_test_payment": "Confirm test payment",
        "deposit_step": "Test mode. The next step is making a deposit.",
        "payment_step": "Test deposit recorded. Confirm the payment.",
        "waiting_draw": "Congratulations! Please wait for the draw to begin. The draw will take place: {draw_datetime}",
        "decline_complete": "Thank you for your generosity and for helping our ecosystem grow! You will receive karma points.",
        "status_waiting_draw": "Waiting for the draw",
        "status_declined": "Prize declined",
        "draw_finished": "The draw is complete. Participation in the next round is available again.",
        "draw_winner": "Congratulations on your win! Test result: you were selected as this round's winner.",
        "draw_not_winner": "The test draw is complete. You were not selected this time. Your coefficient was increased for the next round.",
        "test_notice": "⚠️ TEST VERSION\nNo payment systems, real payments, financial transactions, or links are used. The bot does not request payment details, card data, documents, or passwords. All buttons are for testing only. No financial transactions will take place.",
    },
    "es": {
        "menu": "Menú principal de TrueLoto",
        "participate": "Participar",
        "status": "Mi estado",
        "rules": "Reglas",
        "language_selection": "Selección de idioma",
        "back": "⬅️ Atrás",
        "participate_soon": "La participación estará disponible pronto.",
        "rules_text": "Las reglas de TrueLoto se publicarán antes del inicio de la primera ronda.",
        "name": "Nombre",
        "registration_date": "Fecha de registro",
        "participation_status": "Estado de participación",
        "winning_chance": "Probabilidad de ganar",
        "not_participating": "No participa",
        "language_selected": "Idioma seleccionado: Español.",
        "choose_participation": "Elige una opción de participación:",
        "join_draw": "Participar en el sorteo",
        "decline_prize": "Rechazar el premio",
        "test_deposit": "Hacer un depósito de prueba",
        "confirm_test_payment": "Confirmar pago de prueba",
        "deposit_step": "Modo de prueba. El siguiente paso es hacer un depósito.",
        "payment_step": "Depósito de prueba registrado. Confirma el pago.",
        "waiting_draw": "¡Felicidades! Espera el inicio del sorteo. El sorteo tendrá lugar: {draw_datetime}",
        "decline_complete": "¡Gracias por tu generosidad y por ayudar al desarrollo de nuestro ecosistema! Recibirás puntos de karma.",
        "status_waiting_draw": "Esperando el sorteo",
        "status_declined": "Premio rechazado",
        "draw_finished": "El sorteo ha finalizado. La participación en la próxima ronda vuelve a estar disponible.",
        "draw_winner": "¡Felicidades por tu victoria! Resultado de prueba: fuiste seleccionado como ganador de esta ronda.",
        "draw_not_winner": "El sorteo de prueba ha finalizado. Esta vez no fuiste seleccionado. Tu coeficiente aumentó para la próxima ronda.",
        "test_notice": "⚠️ VERSIÓN DE PRUEBA\nNo se utilizan sistemas de pago, pagos reales, transacciones financieras ni enlaces. El bot no solicita datos de pago, tarjetas, documentos ni contraseñas. Todos los botones son solo para pruebas. No se realizará ninguna operación financiera.",
    },
    "hy": {
        "menu": "TrueLoto-ի գլխավոր մենյու",
        "participate": "Մասնակցել",
        "status": "Իմ կարգավիճակը",
        "rules": "Կանոններ",
        "language_selection": "Լեզվի ընտրություն",
        "back": "⬅️ Հետ",
        "participate_soon": "Մասնակցության հնարավորությունը շուտով հասանելի կլինի։",
        "rules_text": "TrueLoto-ի կանոնները կհրապարակվեն առաջին փուլի մեկնարկից առաջ։",
        "name": "Անուն",
        "registration_date": "Գրանցման ամսաթիվ",
        "participation_status": "Մասնակցության կարգավիճակ",
        "winning_chance": "Հաղթելու հավանականություն",
        "not_participating": "Չեք մասնակցում",
        "language_selected": "Լեզուն ընտրված է՝ հայերեն։",
        "choose_participation": "Ընտրեք մասնակցության տարբերակը․",
        "join_draw": "Մասնակցել խաղարկությանը",
        "decline_prize": "Հրաժարվել շահումից",
        "test_deposit": "Կատարել փորձնական ավանդ",
        "confirm_test_payment": "Հաստատել փորձնական վճարումը",
        "deposit_step": "Փորձնական ռեժիմ։ Հաջորդ քայլը ավանդի կատարումն է։",
        "payment_step": "Փորձնական ավանդը նշված է։ Հաստատեք վճարումը։",
        "waiting_draw": "Շնորհավորում ենք։ Սպասեք խաղարկության մեկնարկին։ Խաղարկությունը կկայանա՝ {draw_datetime}",
        "decline_complete": "Շնորհակալություն ձեր ազնվության և մեր էկոհամակարգի զարգացմանն աջակցելու համար։ Ձեզ կշնորհվեն կարմայի միավորներ։",
        "status_waiting_draw": "Սպասում եք խաղարկությանը",
        "status_declined": "Հրաժարվել եք շահումից",
        "draw_finished": "Խաղարկությունն ավարտվել է։ Հաջորդ փուլին մասնակցությունը կրկին հասանելի է։",
        "draw_winner": "Շնորհավորում ենք հաղթանակի կապակցությամբ։ Փորձնական արդյունք․ դուք ընտրվել եք այս փուլի հաղթող։",
        "draw_not_winner": "Փորձնական խաղարկությունն ավարտվել է։ Այս անգամ դուք չեք ընտրվել հաղթող։ Հաջորդ փուլի համար ձեր գործակիցն ավելացվել է։",
        "test_notice": "⚠️ ՓՈՐՁՆԱԿԱՆ ՏԱՐԲԵՐԱԿ\nՉեն օգտագործվում վճարային համակարգեր, իրական վճարումներ, ֆինանսական գործարքներ կամ հղումներ։ Բոտը չի պահանջում վճարային տվյալներ, քարտի տվյալներ, փաստաթղթեր կամ գաղտնաբառեր։ Բոլոր կոճակները միայն փորձարկման համար են։ Ֆինանսական գործարքներ չեն իրականացվելու։",
    },
}


def text_for(language_code: str | None) -> dict[str, str]:
    """Возвращает тексты выбранного языка, по умолчанию — русские."""
    return TEXTS.get(language_code or "ru", TEXTS["ru"])


def language_keyboard(language_code: str | None = None) -> ReplyKeyboardMarkup:
    """Создаёт нижнюю клавиатуру выбора языка."""
    texts = text_for(language_code)
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=LANGUAGE_NAMES["ru"])],
            [KeyboardButton(text=LANGUAGE_NAMES["en"])],
            [KeyboardButton(text=LANGUAGE_NAMES["es"])],
            [KeyboardButton(text=LANGUAGE_NAMES["hy"])],
            [KeyboardButton(text=texts["back"])],
        ],
        resize_keyboard=True,
    )
